name: vitessce-python-dev
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.8
 - numpy>=1.21.2
 - pandas>=1.3.3
 - scipy>=1.0.0
 - anndata>=0.7.4
 - zarr>=2.5.0
 - numcodecs>=0.7.2
 - nbsphinx==0.8.5
 - pandoc>=2.14.2
 - pytest>=6.2.4
 - jupyterlab==3.1.14
 - jupyter_server==1.11.0
 - traitlets==4.3.3
 - markupsafe==2.0.1
 - pip
 - pip:
   - build==0.1.0
   - loompy>=3.0.6
   - sphinx==4.2.0
   - sphinx-rtd-theme==1.0.0
   - nbclean==0.3.2
   - generate-tiff-offsets>=0.1.7
